# Form implementation generated from reading ui file 'E:\Naveen_Python_coding\pdf_Handler\pdf_UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_pdf_Handler(object):
    def setupUi(self, pdf_Handler):
        pdf_Handler.setObjectName("pdf_Handler")
        pdf_Handler.resize(599, 294)
        self.centralwidget = QtWidgets.QWidget(parent=pdf_Handler)
        self.centralwidget.setObjectName("centralwidget")
        self.pdf_Powerpoint_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pdf_Powerpoint_Button.setGeometry(QtCore.QRect(150, 20, 140, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pdf_Powerpoint_Button.setFont(font)
        self.pdf_Powerpoint_Button.setObjectName("pdf_Powerpoint_Button")
        self.pdf_Doc_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pdf_Doc_Button.setGeometry(QtCore.QRect(10, 20, 130, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pdf_Doc_Button.setFont(font)
        self.pdf_Doc_Button.setObjectName("pdf_Doc_Button")
        self.pdf_Merge_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pdf_Merge_Button.setGeometry(QtCore.QRect(450, 20, 140, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pdf_Merge_Button.setFont(font)
        self.pdf_Merge_Button.setObjectName("pdf_Merge_Button")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 130, 580, 150))
        self.textBrowser.setObjectName("textBrowser")
        self.status_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.status_Label.setGeometry(QtCore.QRect(10, 100, 80, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.status_Label.setFont(font)
        self.status_Label.setObjectName("status_Label")
        self.pdf_Unlock_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pdf_Unlock_Button.setGeometry(QtCore.QRect(300, 20, 140, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pdf_Unlock_Button.setFont(font)
        self.pdf_Unlock_Button.setObjectName("pdf_Unlock_Button")

        self.retranslateUi(pdf_Handler)
        QtCore.QMetaObject.connectSlotsByName(pdf_Handler)

    def retranslateUi(self, pdf_Handler):
        _translate = QtCore.QCoreApplication.translate
        pdf_Handler.setWindowTitle(_translate("pdf_Handler", "PDF_HANDLER"))
        self.pdf_Powerpoint_Button.setText(_translate("pdf_Handler", "PDF to PowerPoint"))
        self.pdf_Doc_Button.setText(_translate("pdf_Handler", "PDF to Doc"))
        self.pdf_Merge_Button.setText(_translate("pdf_Handler", "Merge PDF"))
        self.status_Label.setText(_translate("pdf_Handler", "STATUS"))
        self.pdf_Unlock_Button.setText(_translate("pdf_Handler", "Unlock PDF"))
